= Υπολογιστική Νέφους και Υπηρεσίες
:toc:
:toc-title: Πίνακας Περιεχομένων

.ΕΡΓΑΣΤΗΡΙΟ ΜΑΘΗΜΑΤΟΣ
[ΝΟΤΕ]
*****
[.text-center]
ΆΣΚΗΣΗ 2024

Στο συγκεκριμένο project κληθήκαμε να φτιάξουμε ένα εικονικό εργαστήριο Vlab σε περιβάλλον 
*docker* που θα εκτελεί αυτόματα τις λειτουργίες που διαθέτει. 
*****

Μακρύγιαννης Σταύρος – 20390137 +
Κάρλες Γεώργιος - 20390093


== Εισαγωγή
=== Περιγραφή

Για την συγκεκριμένη εφαρμογή χρησιμοποιήθηκαν οι εξής τεχνολογίες: Για την ανάπτυξη του back-end της εφαρμογής έγινε με χρήση του https://flask.palletsprojects.com/en/2.0.x/[*Flask*], ένα Python framework για την δημιουργία RESTful APIs. Η ανάπτυξη του front-end της εφαρμογής έγινε με https://vuejs.org/[*Vue.js*], JavaScript framework για την δημιουργία του UI της εφαρμογής. Η εφαρμογή είναι πλήρως dockerized και όλες οι υπηρεσίες τρέχουν σε https://www.docker.com/[*Docker*] containers.

=== Εγκατάσταση

Για την Εγκατάσταση της εφαρμογής ακολουθήστε τα παρακάτω βήματα

Πρώτα κάνουμε clone το repository:

```
git clone https://github.com/MakrygiannisStavros/CloudProject2024.git
```

Και στην συνέχεια κάνουμε deploy τρέχοντας:

```
docker-compose up --build --force-recreate
```

NOTE: Πρέπει πρώτα να έχει γίνει η εγκατάσταση του *Docker* και *docker-compose*.

== Δημιουργία εικονικού εργαστηρίου

=== Δικτυο

Το εικονικό μας εργαστήριο έχει 2 υπηρεσίες που όμως έχουμε δώσει ένα δίκτυο στο οποίο τρέχουν και τα 2 containers. Η δήλωση έχει γίνει μέσα στο αρχείο *docker-compose.yml* για το κάθε service.

```
networks:
  vlab:
```

=== Χώρος αποθήκευσης

Στο εικονικό εργαστήριο εχουμε δωσει κοινο χωρο αποθήκευσης και στις 2 υπηρεσίες, Αυτο μπορουμε να το δουμε παλι στο στο αρχείο *docker-compose.yml*.

```
volumes:
  vlab_volume:
```
