version: '3'

services:
  web:
    build: ./web
    ports:
      - "8000:8000"
    volumes:
      - ./vlab_network:/shared
    networks:
      - vlab

  frontend:
    build: ./client
    ports:
      - "8080:80"
    volumes:
      - ./vlab_volume:/shared
    networks:
      - vlab

volumes:
  vlab_volume:

networks:
  vlab: